### ISSUE TITLE
image included in 'src' attribute of image tag won't be copied to dist folder

### ISSUE THREAD

**Issue by craigcosmo** [webpack/file-loader#111] opened 2016-12-31 16:13 UTC
this is a piece of my webpack.config.js

```js
{
	test: /\.(jpe?g|gif|png|svg)$/i,
	use: 'file-loader?name=/image/[name].[ext]'
}
```
When I have css style like this

**style.scss**
```css
div{
  background: url(./image/banner.png)
}
```
The banner.png will be copy to `dist/image` folder when build, which is good, which is what I expected

But when I have this

**AccountComponent.jsx** 
```html
<div class="maincontainer">
...
   <div><img src="./image/box.png" /></div>
...
</div>
```
When build, the `box.png` won't be copied to `dist/image` folder. Which is problem.

**Comment by SpaceK33z** [comment] 2017-01-01 14:31
Dupe of https://github.com/webpack/file-loader/issues/93

**Closed by SpaceK33z** 2017-01-01 14:31 UTC

**Comment by craigcosmo** [comment] 2017-01-01 17:09
Thanks for the comment, but I don't see how this issue is the same as #93 
in #93 the the image got corrupted. In this issue the image is not copied to distribution folder.

**Comment by SpaceK33z** [comment] 2017-01-01 17:13
You're right. This is not a bug, you're using it wrong. You need to import the image like this:

```js
import BoxImg './image/box.png';
...
<img src={BoxImg} />
```
