### ISSUE TITLE
Output files to a different dir

### ISSUE THREAD

**Issue by guocheng** [webpack/file-loader#32] opened 2015-07-31 09:46 UTC
Hello,

I am building an web app using bootstrap. I had this line to include the .css file

```
var Bootstrap  = require('../../node_modules/bootstrap/dist/css/bootstrap.min.css');
```

I would like to output the corresponding font files that `bootstrap.min.css` relies on to `/dist/css/`

Here is a simplified version of my webpack.config.js:

```
module.exports = {
    entry: {
        app: path.resolve(__dirname, 'app/src/index.js'),
    },
    output: {
        path: path.resolve(__dirname, 'dist'),
        filename: '../js/[name].js'
    },
    module: {
        loaders:[{
            test: /\.(ttf|eot|svg)(\?v=[0-9]\.[0-9]\.[0-9])?$/,
            loader: 'file-loader'
        }]
```

How can I config file-loader to output the font files to `/dist/css` instead of `/dist/`?

Thank you!

**Comment by hkongm** [comment] 2015-08-19 09:00
same question.

**Comment by qiankun007** [comment] 2015-08-20 11:06
it is not a bug, you can add a query parameter `name=xxx` like this   
```
    {
                test: /\.(png|jpg)$/,
                loader: 'url-loader?limit=100000&name=./imgs/[hash].[ext]'
    }
``` 

see [loader-utils](https://github.com/webpack/loader-utils) source code

**Comment by dropfen** [comment] 2016-09-29 23:43
If you want for example emit your files at *fonts/some-font.ttf* 
`loader: "file?name=./fonts/[hash].[ext]"`
But you are already extracting your css into *css/styles.css* 
`new ExtractTextPlugin('css/app.css', { allChunks: true })` 

Your css files will try load the fonts from css/fonts/... 
Because they expect to be in the root of the public folder.

You can fix this by giving the `publicPath` query to the **file-loader**

`loader: "file?pubicPath=../&name=./fonts/[hash].[ext]"`

This will emit the files in .fonts/* and but the publicPath will be .././fonts/** in your css file..

Maybe it helps some one..

**Comment by lpil** [comment] 2016-10-03 14:18
Thanks for the tip! It would be great if this option was documented in the README.

**Comment by SpaceK33z** [comment] 2016-10-09 08:38
Closing since the question has been answered. Feel free to add this to the readme with a PR.

**Closed by SpaceK33z** 2016-10-09 08:38 UTC

**Comment by davevans** [comment] 2016-10-19 23:04
ps: the param to the **file-loader** is publicPath - beware cut and paste of pubicPath from above

**Comment by sputinyk** [comment] 2016-10-23 16:14
@dropfen ,  publicPath QueryString, best tip ever. Thanks!

**Comment by tomwang1013** [comment] 2017-01-26 15:16
we can also set the publicPath to an absolute path, so the assets can be accessed by all css

**Comment by jimmerioles** [comment] 2017-10-20 08:12
that sneaky `publicPath=../` :satisfied:
